(()=>{var e={};e.id=628,e.ids=[628],e.modules={846:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},3033:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-unit-async-storage.external.js")},3295:e=>{"use strict";e.exports=require("next/dist/server/app-render/after-task-async-storage.external.js")},4870:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},6265:(e,t,r)=>{"use strict";r.r(t),r.d(t,{patchFetch:()=>S,routeModule:()=>d,serverHooks:()=>h,workAsyncStorage:()=>m,workUnitAsyncStorage:()=>g});var s={};r.r(s),r.d(s,{POST:()=>l,dynamic:()=>p});var n=r(6559),a=r(8088),i=r(7719),o=r(2190);let p="force-dynamic";function c(e){return String(e||"").trim().toLowerCase()}function u(e){return String(e||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}async function l(e){try{let t=await e.json(),r=function(e){let t={},r=String(e.name||"").trim(),s=c(e.email),n=String(e.company||"").trim(),a=String(e.phoneNumber||"").trim(),i=String(e.message||"").trim(),o=!!e.agreed;return r.length<2&&(t.name="お名前を入力してください。"),/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)||(t.email="有効なメールアドレスを入力してください。"),a.replace(/[^\d]/g,"").length<8&&(t.phoneNumber="有効な電話番号を入力してください。"),i.length<5&&(t.message="お問い合わせ内容を入力してください。"),o||(t.agreed="同意が必要です。"),{isValid:0===Object.keys(t).length,errors:t,clean:{name:r,email:s,company:n,phoneNumber:a,message:i,agreed:o}}}(t);if(!r.isValid)return o.NextResponse.json({ok:!1,errors:r.errors},{status:400});let s=process.env.RESEND_API_KEY,n=process.env.ACCESS_FROM_EMAIL,a=(process.env.ACCESS_RECEIVING_EMAIL||process.env.ACCESS_RECIVING_EMAIL||process.env.ACCESS_ADMIN_EMAIL||"").split(/[,\n;\s]+/).map(e=>c(e)).filter(Boolean),i=new Date().toLocaleString("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",timeZone:"Asia/Tokyo"});if(!s||!n||0===a.length)return o.NextResponse.json({ok:!1,message:"メール送信設定が未完了です。時間をおいて再度お試しください。"},{status:500});let p=`
      <div style="font-family: 'Hiragino Sans', 'Noto Sans JP', sans-serif; color: #111; line-height: 1.8;">
        <p>お問い合わせフォームを受信しました。</p>
        <p>お名前: ${u(r.clean.name)}</p>
        <p>メールアドレス: ${u(r.clean.email)}</p>
        <p>会社名: ${u(r.clean.company||"-")}</p>
        <p>電話番号: ${u(r.clean.phoneNumber)}</p>
        <p>プライバシーポリシー同意: 同意済み</p>
        <p>同意時刻: ${u(i)} (JST)</p>
        <p>お問い合わせ内容:</p>
        <p style="white-space: pre-wrap;">${u(r.clean.message)}</p>
      </div>
    `,l=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${s}`,"Content-Type":"application/json"},body:JSON.stringify({from:n,to:a,reply_to:r.clean.email,subject:"【受信通知】THE SILENCE お問い合わせフォーム",html:p})});if(!l.ok){let e=await l.text();throw Error(`Contact email delivery failed: ${l.status} ${e}`)}return o.NextResponse.json({ok:!0})}catch(e){return console.error("[contact/request] failed",e),o.NextResponse.json({ok:!1,message:"送信に失敗しました。時間をおいて再度お試しください。"},{status:500})}}let d=new n.AppRouteRouteModule({definition:{kind:a.RouteKind.APP_ROUTE,page:"/api/contact/request/route",pathname:"/api/contact/request",filename:"route",bundlePath:"app/api/contact/request/route"},resolvedPagePath:"/Users/taishu/timelesscondminium/timelesscondminium/app/api/contact/request/route.js",nextConfigOutput:"",userland:s}),{workAsyncStorage:m,workUnitAsyncStorage:g,serverHooks:h}=d;function S(){return(0,i.patchFetch)({workAsyncStorage:m,workUnitAsyncStorage:g})}},6487:()=>{},8335:()=>{},9294:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-async-storage.external.js")}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[447,580],()=>r(6265));module.exports=s})();