import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { createService, validSlug } from '../lib/affiliate/service.mjs';
import { digest, totp, readReferral, signReferral } from '../lib/affiliate/crypto.mjs';

const password = 'A-long-test-passphrase-2026!';
const config = { secret: 'test-only-secret-0000000000000000000000000000', origin: 'https://example.test', adminPath: 'test-admin-path-0123456789012345' };
const tokenOf = url => new URLSearchParams(new URL(url).hash.slice(1)).get('token');
test('portal security and referral lifecycle on real PostgreSQL semantics', async t => {
  const db = new PGlite();
  t.after(() => db.close());
  await db.exec(await readFile(new URL('../lib/affiliate/schema.sql', import.meta.url), 'utf8'));
  const service = createService({ db, ...config });
  const setup = await service.bootstrap('admin@example.test');
  const adminToken = tokenOf(setup.setupUrl);
  const info = await service.inviteInfo(adminToken, 'admin');
  assert.ok(info.setup.secret);
  await assert.rejects(service.activate({ token: adminToken, password, code: 'bad' }, 'admin'), /6桁/);
  const adminSetup = await service.activate({ token: adminToken, password, code: totp(info.setup.secret).generate() }, 'admin');
  const admin = await service.getActor(adminSetup.session.value);
  assert.equal(admin.role, 'admin');
  assert.equal(adminSetup.recoveryCodes.length, 8);
  await assert.rejects(service.activate({ token: adminToken, password }, 'admin'), /使用/);
  await assert.rejects(service.bootstrap('attacker@example.test'), /登録/);
  const a = await service.createUser(admin, { name: '担当者A', email: 'A@example.test', company: '京都パートナー' });
  const b = await service.createUser(admin, { name: '担当者B', email: 'b@example.test', company: '東京パートナー' });
  const activate = inviteUrl => service.activate({ token: tokenOf(inviteUrl), password }, 'partners');
  const authA = await activate(a.inviteUrl); const authB = await activate(b.inviteUrl);
  const userA = await service.getActor(authA.session.value); const userB = await service.getActor(authB.session.value);
  await t.test('roles, account isolation and unique custom names', async () => {
    await assert.rejects(service.createUser(userA, { email: 'evil@example.test', name: 'evil' }), e => e.status === 403);
    await assert.rejects(service.updateUser(userA, userB.id, { active: false }), e => e.status === 403);
    const created = await service.createLink(userA, { slug: 'yamada-kyoto', label: '京都のご紹介' });
    assert.equal(created.url, 'https://example.test/r/yamada-kyoto');
    assert.equal(created.link.user_id, userA.id);
    await assert.rejects(service.createLink(userB, { slug: 'YAMADA-KYOTO', label: 'duplicate' }), e => e.status === 409);
    await assert.rejects(service.updateLink(userB, created.link.id, { label: 'hijacked' }), e => e.status === 404);
    assert.equal((await service.dashboard(userB)).links.length, 0);
    assert.deepEqual((await service.dashboard(userA)).users, []);
    assert.equal((await service.dashboard(admin)).users.length, 2);
    assert.ok(!(await service.dashboard(admin)).users.some(u => 'password_hash' in u || 'mfa_secret' in u));
    assert.equal((await service.publicLink('yamada-kyoto')).name, '担当者A');
    const signed = signReferral(created.link.id, config.secret);
    assert.equal((await service.attribution(signed)).company, '京都パートナー');
    assert.equal(await service.attribution(signed + 'x'), null);
    assert.equal(readReferral(signReferral(created.link.id, config.secret, Date.now() - 91 * 86400000), config.secret), null);
    await service.updateLink(userA, created.link.id, { active: false });
    assert.equal(await service.publicLink('yamada-kyoto'), undefined);
    assert.equal(await service.attribution(signed), undefined);
    await assert.rejects(service.createLink(userB, { slug: 'yamada-kyoto', label: 'reuse' }), e => e.status === 409);
    await service.updateLink(userA, created.link.id, { active: true });
    await service.updateUser(admin, userA.id, { active: false });
    assert.equal(await service.getActor(authA.session.value), null);
    assert.equal(await service.publicLink('yamada-kyoto'), undefined);
    assert.equal(await service.attribution(signed), undefined);
    await assert.rejects(service.createLink(userA, { slug: 'stale-session', label: 'stale' }), e => e.status === 401);
    await service.updateUser(admin, userA.id, { active: true });
  });
  await t.test('MFA, private administrator entrance, replay protection and recovery codes', async () => {
    await assert.rejects(service.login({ email: admin.email, password, code: adminSetup.recoveryCodes[0] }, 'mfa'), e => e.status === 401);
    await assert.rejects(service.login({ email: admin.email, password, adminKey: config.adminPath, code: '000000invalid' }, 'mfa'), e => e.status === 401);
    const auth = await service.login({ email: admin.email, password, adminKey: config.adminPath, code: adminSetup.recoveryCodes[0] }, 'mfa');
    assert.equal((await service.getActor(auth.session.value)).role, 'admin');
    await assert.rejects(service.login({ email: admin.email, password, adminKey: config.adminPath, code: adminSetup.recoveryCodes[0] }, 'mfa'), e => e.status === 401);
    await db.query('UPDATE affiliate_users SET last_totp_step=-1 WHERE id=$1', [admin.id]);
    const currentCode = totp(info.setup.secret).generate();
    await service.login({ email: admin.email, password, adminKey: config.adminPath, code: currentCode }, 'mfa');
    await assert.rejects(service.login({ email: admin.email, password, adminKey: config.adminPath, code: currentCode }, 'mfa'), e => e.status === 401);
    await service.logout(auth.session.value);
    assert.equal(await service.getActor(auth.session.value), null);
    const stored = (await db.query('SELECT hash FROM affiliate_sessions')).rows;
    assert.ok(stored.every(s => !s.hash.includes(auth.session.value)));
  });
  await t.test('invitations expire, are single-use, and replacement revokes older invitations and sessions', async () => {
    const first = await service.reissue(admin, userB.id);
    const second = await service.reissue(admin, userB.id);
    await assert.rejects(service.inviteInfo(tokenOf(first.inviteUrl), 'reset'), e => e.status === 410);
    await activate(second.inviteUrl);
    assert.equal(await service.getActor(authB.session.value), null);
    await assert.rejects(activate(second.inviteUrl), e => e.status === 410);
    const expired = await service.reissue(admin, userB.id);
    await db.query("UPDATE affiliate_invites SET expires_at=now()-interval '1 hour' WHERE hash=$1", [digest(tokenOf(expired.inviteUrl))]);
    await assert.rejects(service.inviteInfo(tokenOf(expired.inviteUrl), 'reset'), e => e.status === 410);
    const stopped = await service.reissue(admin, userB.id);
    await service.updateUser(admin, userB.id, { active: false });
    await assert.rejects(service.inviteInfo(tokenOf(stopped.inviteUrl), 'reset'), e => e.status === 410);
  });
  await t.test('atomic unique constraint and persistent rate limits', async () => {
    const results = await Promise.allSettled([service.createLink(userA, { slug: 'same-url-name', label: 'one' }), service.createLink(userA, { slug: 'same-url-name', label: 'two' })]);
    assert.equal(results.filter(r => r.status === 'fulfilled').length, 1);
    assert.equal(results.find(r => r.status === 'rejected').reason.status, 409);
    const attempts = await Promise.allSettled(Array.from({ length: 10 }, () => service.limit('race', 'same-ip', 5)));
    assert.equal(attempts.filter(r => r.status === 'fulfilled').length, 5);
    const otherInstance = createService({ db, ...config });
    await assert.rejects(otherInstance.limit('race', 'same-ip', 5), e => e.status === 429);
    await db.query("UPDATE affiliate_sessions SET expires_at=now()-interval '1 second'");
    assert.equal(await service.getActor(adminSetup.session.value), null);
  });
});
test('URL names reject reserved paths, traversal and invalid names', () => {
  for (const name of ['../admin', 'admin', 'api', '日本語', '-abc', 'abc-', 'two--parts', 'a'.repeat(49), 'ab', 'with space', 'x?y=1']) assert.equal(validSlug(name), false, name);
  assert.equal(validSlug('tanaka-kyoto'), true);
});
